version: '3'

services:
  redis:
    image: redis:5.0.0
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    privileged: true
    command: redis-server /etc/redis/redis.conf --appendonly yes
    volumes:
      - ./conf/redis.conf:/etc/redis/redis.conf
      - ./data:/data
      - /etc/localtime:/etc/localtime
    environment:
      TIME_ZONE: Asia/Shanghai
